### PR TITLE
Various fixes

### LINKED ISSUE #123: Page change causes rerender of drawer animation
Navigating from one doc page to the other causes annoying re-renders.

### PR DESCRIPTION
**Pull request by KilDesu**
## PR Type

> What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## What's new?

> List the changes

- Fix the problem where changing doc page would rerender the whole layout
- Remove unnecessary code
- Fix some styles
- Fix color page to improve contrast between text and bg in palettes
- Avoid binding multiple dialog and drawer components to the same variable (would induce bugs otherwise)

## Screenshots

> If needed, you can add screenshots here

N/A

## This pull request closes an issue

> Add `Closes`, `Fixes` or `Resolves` followed by `#xxx[,#xxx]` where "xxx" is the issue number

Closes #123, #124

### CODE REVIEW

File: src/lib/components/drawer/QDrawer.svelte [hunk 1]
```diff
@@ -109,24 +109,14 @@
...
   const style = $derived(`${drawerWidthStyle}${props.style ?? ""}`);
 
-  function handleClickInside(e: MouseEvent) {
-    e.stopPropagation();
-  }
-
-  function tryClose() {
-    if (canHideOnClickOutside) {
+  function tryClose(e: MouseEvent) {
+    if (canHideOnClickOutside && e.target !== drawerEl && !drawerEl.contains(e.target as Node)) {
```
Comment (therealcoder1337) [inline src/lib/components/drawer/QDrawer.svelte:113]: It's not really clear what is happening here, please refactor if possible (extract to descriptive variables).

File: src/routes/colors/+page.svelte [hunk 2]
```diff
@@ -20,6 +20,14 @@
     "blue-grey",
     "grey",
   ];
+
+  const textColor = (color: string, step: number) => {
+    if (step <= 5 + Number(["lime", "yellow"].includes(color))) {
```
Comment (therealcoder1337) [inline src/routes/colors/+page.svelte:25]: Could also use some refactoring for clarity of what/why. And using ternary.

File: src/routes/colors/+page.svelte [hunk 3]
```diff
@@ -28,10 +36,11 @@
   <div class="row q-gutter-md">
     {#each colors as color (color)}
       <div class="col-xs-12 col-sm-6 col-md-3 col-lg-2 palette">
-        <div class="bg-{color} text-grey-10 heading q-pa-sm">{color}</div>
-        {#each [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as step (step)}
-          <div class="bg-{color}-{step} q-pa-sm {step < 5 ? 'text-grey-8' : ''}">
-            {color}-{step}
+        <div class="bg-{color} text-{color}-10 title-large q-pa-sm">{color}</div>
+        {#each { length: 10 }, step (step)}
+          {@const stepp = step + 1}
```
Comment (therealcoder1337) [inline src/routes/colors/+page.svelte:41]: Uhm... Possible to improve?

**Review by therealcoder1337 — APPROVED** [review]
