### PR TITLE
Snippets fix

### LINKED ISSUE #100: Find a good way to show custom types to user
As the title says, it would be great to find a good way to be able to show the users the definition of Quaff's custom types.
Today, we have a semi-working solution that stops working for nested types and when more or less complex union types are involved

### PR DESCRIPTION
**Pull request by KilDesu**
## PR Type

> What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## What's new?

> List the changes

- Replaced slots by snippets in the API docs
- Made snippets docs generation automatic (as opposed to slots)
- Improved the type checker inside API
- Replaced drawer displaying types definition on click by a tooltip (on mouseenter)
- Fixed some components that didn't work
- Made all component docs work with the new docs gen api
- Import "shiki" when `code` changes inside `QCodeBlock` instead of onMount

## Screenshots

> If needed, you can add screenshots here

N/A

## This pull request closes an issue

> Add `Closes`, `Fixes` or `Resolves` followed by `#xxx[,#xxx]` where "xxx" is the issue number

Closes #100

### CODE REVIEW

File: src/lib/components/list/props.ts [hunk 1]
```diff
@@ -8,14 +8,7 @@ export interface QListProps extends HTMLAttributes<HTMLElement> {
...
   separator?: boolean;
-  separatorOptions?: {
-    spacing?: QSeparatorProps["spacing"];
-    inset?: QSeparatorProps["inset"];
-    color?: QSeparatorProps["color"];
-    size?: QSeparatorProps["size"];
-    text?: QSeparatorProps["text"];
-    textAlign?: QSeparatorProps["textAlign"];
-  };
+  separatorOptions?: Exclude<QSeparatorProps, "vertical">;
```
Comment (therealcoder1337) [inline src/lib/components/list/props.ts:11]: Not sure, but wouldn't this be `Omit` instead of `Exclude`?

Comment (KilDesu) [reply src/lib/components/list/props.ts:11]: True, you're right

File: src/lib/components/private/QApi.svelte [hunk 2]
```diff
@@ -1,78 +1,154 @@
...
+            },
+          });
+        });
+      });
+    });
+  }
+
+  $effect(() => {
+    // Doesn't rerun if we don't use JSON.stringify
+    void JSON.stringify(api);
```
[the remark this answers is not in the document]
Comment (KilDesu) [reply src/lib/components/private/QApi.svelte:148]: It's not obligatory but I found myself use it recently. I can remove it though.
I don't think there's any real difference to using it or not.

File: src/lib/components/private/QApi.svelte [hunk 3]
```diff
@@ -1,78 +1,154 @@
...
+    ) => `<span${className(typeStyle, isClickable, typeName)}>${spanContent}</span>`;
+
+    let content = "<pre>";
+
+    if (prop.optional) {
+      content += inSpan("?", { typeStyle: true });
+    }
+
+    if (!Array.isArray(prop.type) || prop.type.length) {
+      content += inSpan(":\u00A0");
```
Comment (therealcoder1337) [inline src/lib/components/private/QApi.svelte:61]: `\u00A0` is quite incomprehensible.

File: src/lib/components/private/QApi.svelte [hunk 4]
```diff
@@ -1,78 +1,154 @@
...
+      content += inSpan(Array.isArray(prop.type) ? "(" : "", { typeStyle: true });
     }
 
-    if (!drawer[QDocument.name][doc.name]) {
-      setTimeout(() => {
-        drawerContent = content;
-        drawer[QDocument.name][doc.name] = true;
-      }, 100);
+    if (prop.isSnippet && Array.isArray(prop.type) && prop.type.length) {
+      content += inSpan("{\u00A0", { typeStyle: true });
```
Comment (therealcoder1337) [inline src/lib/components/private/QApi.svelte:69]: Same here, can we have a variable that explains what `\u00A0` is?

File: src/lib/components/private/QApi.svelte (hunk 3 above)
Comment (KilDesu) [reply src/lib/components/private/QApi.svelte]: It's a space. I used it because a simple " " didn't work in the markup but now I moved the api creation inside JS, I can use a simple " " and remove those.

File: src/lib/components/private/QApi.svelte (hunk 4 above)
Comment (KilDesu) [reply src/lib/components/private/QApi.svelte]: Removed it

**Review by therealcoder1337 — APPROVED** [review]
